version: '3.0'

services:
  app:
    restart: always
    build: .   
    ports:
     - "3000:3000"
    environment:
     - NODE_ENV=development     
    links: 
     - mongodb

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
     - "27017:27017"
